name: Auto Fork Merge

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 기본Repository Branch commit check
        id: step1
        uses: devload/action_branch_sha@main
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}
          owner: onycom-imqa
          repository: IMQA-Android-Core
          branch: master
          shaKey: upstreamRepoKey
      - name: Get color
        run: echo "기본Repository Branch commit Hash is ${{ steps.step1.outputs.upstreamRepoKey }}"
      - name: Fork Repository Branch commit check
        uses: devload/action_branch_sha@main
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}
          owner: onycom-imqa
          repository: IMQA-Android-Core_QA
          branch: master
          shaKey: ForkRepoKey
