name: Auto Fork Merge

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Target Repository Branch commit check
        id: target_action
        uses: devload/auto_fork_pr@find_branch_hash
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}
          owner: onycom-imqa
          repository: IMQA-Android-Core
          branch: master
          shaKey: upstreamRepoKey
      - name: Target Hash Print
        run: echo "Target Repository Branch commit Hash is ${{ steps.target_action.outputs.result }}"
      - name: Fork Repository Branch commit check
        id: fork_action
        uses: devload/auto_fork_pr@find_branch_hash
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}
          owner: onycom-imqa
          repository: IMQA-Android-Core_QA
          branch: master
          shaKey: ForkRepoKey
      - name: Fork Hash Print
        run: echo "Fork Repository Branch commit Hash is ${{ steps.fork_action.outputs.result }}"
      - name: equalCheck
        run: echo "if Check ok"
        if: contains(steps.target_action.outputs.result, steps.fork_action.outputs.result)
      - name: NotequalCheck
        run: echo " Not if Check ok"
        if: !contains(steps.target_action.outputs.result, steps.fork_action.outputs.result)
